apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-api-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: demo-api-dev
    app.xgeeks.org/team: gabtec
    app.xgeeks.org/lifecycle: dev
spec:
  project: idp-dev
  revisionHistoryLimit: 4
  destination:
    server: https://kubernetes.default.svc # cluster API url
    namespace: idp-dev
  source:
    repoURL: https://github.com/gabtec/demo-go-api_deployment.git
    path: k8s/overlays/kbeta
    targetRevision: HEAD
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:
      - allowEmpty=true
  ignoreDifferences:
    # for the specified json pointers
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
