apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-go-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: demo-go-api
spec:
  project: idp-dev
  revisionHistoryLimit: 4
  destination:
    server: https://kubernetes.default.svc # cluster API url
    namespace: idp-dev
  source:
    repoURL: https://github.com/gabtec/demo-go-api_deployment.git
    path: k8s/overlays/dev
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions: # Sync options which modifies sync behavior
      - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
      # - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
      # - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default ).
      # - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
