apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: correio.gab@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod # ---> this is what we will ref in app ingress annotations for cert-manager
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
        selector:
          matchLabels:
            "use-http01-solver": "true"
        # selector:
        #   dnsNames: # because this challenge do not allow wildcard subdomains
        #     - "demo.gabtec.pt"
      - dns01:
        cloudflare:
          email: correio.gab@gmail.com
          apiTokenSecretRef:
            name: cf-api-key-secret
            key: apiKey
        selector:
          dnsZones:
            - "gabtec.fun"
