---
# LINK: https://external-secrets.io/latest/api/clustersecretstore/
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: eso-azure-secret-store
spec:
  provider:
    azurekv:
      # tenant where KV is
      tenantId: d414f860-ce56-418c-8021-0dcb6e93bdee # gabriel acc
      # secret store URL
      vaultUrl: https://gabtec-vault.vault.azure.net
      # CloudEnvType - opts: PubliCloud (default) | GermanCloud | USGovernmentCloud | ChinaCloud
      environmentType: PublicCloud
      # How ESO will connect to Cloud Store
      ## method:
      authType: ServicePrincipal # opts: ServicePrincipal | ManagedIdentity | WorkloadIdentity
      ## credentials file ref:
      authSecretRef:
        clientId:
          name: idp-azure-creds-short-secret # azure-credentials
          key: clientId
          namespace: idp-system
        clientSecret:
          name: idp-azure-creds-short-secret # azure-credentials
          key: clientSecret
          namespace: idp-system
        # name: azure-credentials-short # azure-credentials
        # namespace: external-secrets
        # # will read tenantId, clientId and clientSecret variables from this ServicePrincipal creds file
