# #################################### #
#     Cloufdflare API Token Secret
# #################################### #
# ---
###### --- this is created by gitops-bridge script -----
# apiVersion: v1
# kind: Secret
# metadata:
#   name: cf-api-key-secret
#   namespace: cert-manager #default
# type: Opaque
# stringData:
#   apiKey: abcde

# #################################### #
#        Cluster Issuer
# #################################### #
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    # Email address used for ACME registration
    email: correio.gab@gmail.com
    # The ACME server URL
    ## STAGING server
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    ## PROD server
    server: https://acme-v02.api.letsencrypt.org/directory
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key
      name: letsencrypt-prod-secret
      # name: letsencrypt-staging-secret
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
      - dns01:
          cloudflare:
            email: correio.gab@gmail.com
            apiKeySecretRef:
              name: cf-api-key-secret
              key: apiKey
        # atention: the nest is on same level as dns01:
        selector:
          dnsZones:
            - "gabtec.pt"
